class City {
  String name;
  int id;

  City({required this.name, required this.id});
}

List<City> vietnamCities = [
  City(name: "Hà Nội", id: 1),
  City(name: "Hà Giang", id: 2),
  City(name: "Cao Bằng", id: 4),
  City(name: "Lai Châu", id: 6),
  City(name: "Lào Cai", id: 10),
  City(name: "Tuyên Quang", id: 11),
  City(name: "Điện Biên", id: 12),
  City(name: "Lạng Sơn", id: 14),
  City(name: "Bắc Kạn", id: 17),
  City(name: "Thái Nguyên", id: 19),
  City(name: "Yên Bái", id: 20),
  City(name: "Sơn La", id: 21),
  City(name: "Phú Thọ", id: 25),
  City(name: "Vĩnh Phúc", id: 26),
  City(name: "Quảng Ninh", id: 27),
  City(name: "Bắc Giang", id: 30),
  City(name: "Bắc Ninh", id: 31),
  City(name: "Hải Dương", id: 33),
  City(name: "Hải Phòng", id: 34),
  City(name: "Hưng Yên", id: 35),
  City(name: "Nam Định", id: 36),
  City(name: "Ninh Bình", id: 37),
  City(name: "Thanh Hóa", id: 38),
  City(name: "Nghệ An", id: 40),
  City(name: "Hà Tĩnh", id: 42),
  City(name: "Quảng Bình", id: 44),
  City(name: "Quảng Trị", id: 45),
  City(name: "Thừa Thiên Huế", id: 46),
  City(name: "Đà Nẵng", id: 48),
  City(name: "Quảng Nam", id: 49),
  City(name: "Quảng Ngãi", id: 51),
  City(name: "Bình Định", id: 52),
  City(name: "Phú Yên", id: 54),
  City(name: "Khánh Hòa", id: 56),
  City(name: "Ninh Thuận", id: 58),
  City(name: "Bình Thuận", id: 60),
  City(name: "Kon Tum", id: 62),
  City(name: "Gia Lai", id: 64),
  City(name: "Đắk Lắk", id: 66),
  City(name: "Đắk Nông", id: 67),
  City(name: "Lâm Đồng", id: 68),
  City(name: "Bình Phước", id: 70),
  City(name: "Tây Ninh", id: 72),
  City(name: "Bình Dương", id: 74),
  City(name: "Đồng Nai", id: 75),
  City(name: "Bà Rịa - Vũng Tàu", id: 77),
  City(name: "TP.Hồ Chí Minh", id: 79),
  City(name: "Long An", id: 80),
  City(name: "Tiền Giang", id: 82),
  City(name: "Bến Tre", id: 83),
  City(name: "Trà Vinh", id: 84),
  City(name: "Vĩnh Long", id: 86),
  City(name: "Đồng Tháp", id: 87),
  City(name: "An Giang", id: 89),
  City(name: "Kiên Giang", id: 91),
  City(name: "Cần Thơ", id: 92),
  City(name: "Hậu Giang", id: 93),
  City(name: "Sóc Trăng", id: 94),
  City(name: "Bạc Liêu", id: 95),
  City(name: "Cà Mau", id: 96),
];
